name: Remove release branches after merge

on:
  pull_request:
    types:
      - closed
    branches:
      - 'v**'

jobs:
  remove-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove branch
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ "$BRANCH_NAME" == release-* ]]; then
            echo "Removing branch: $BRANCH_NAME"

            # Remove the remote branch
            git push origin --delete "$BRANCH_NAME"
          else
            echo "Branch '$BRANCH_NAME' does not match 'release-*', skipping."
          fi
