on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  fail_to_start:
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/certora_run.yml
    secrets:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}
    with:
      use-beta: true
      configurations: |-
        tests/conf-start-error.conf
        tests/conf-verified.conf
        tests/conf-violations.conf
        tests/conf-verified.conf
        tests/conf-violations.conf
        tests/conf-start-error.conf
      solc-versions: 0.7.6 0.8.1
      job-name: "Fail to Start"
      server: "vaas-dev"

  violated_rules:
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/certora_run.yml
    secrets:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}
    with:
      configurations: |-
        tests/conf-verified.conf
        tests/conf-violations.conf
        tests/conf-verified.conf
        tests/conf-violations.conf
      solc-versions: 0.7.6 0.8.1
      job-name: "Violated Rules"
      server: "vaas-dev"

  verified_rules:
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/certora_run.yml
    secrets:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}
    with:
      configurations: |-
        tests/conf-verified.conf
        tests/conf-verified.conf
        tests/conf-verified.conf
      solc-versions: 0.7.6 0.8.1
      job-name: "Verified Rules"
      server: "vaas-dev"
