on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-fail:
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/certora_run.yml
    secrets:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}
    with:
      use-beta: true
      configurations: |-
        tests/conf-error.conf
        tests/conf-good.conf
        tests/conf-good.conf
        tests/conf-error.conf
        tests/conf-good.conf
        tests/conf-good.conf
      solc-versions: 0.7.6 0.8.1
      job-name: "Failing Test"

  test-pass:
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/certora_run.yml
    secrets:
      CERTORAKEY: ${{ secrets.CERTORAKEY }}
    with:
      configurations: |-
        tests/conf-good.conf
        tests/conf-good.conf
        tests/conf-good.conf
      solc-versions: 0.7.6 0.8.1
      job-name: "Passing Test"
